services:
  port-checker:
    build: .
    container_name: port-checker
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 